-- Autogenerated by Tools/Mac/uiatlas.  Do not edit manually.

resourceref "Image" "UiMapAtlas1"

resource "ImageRegion" "UiMapPrairie_Village_Shrine" { image = "UiMapAtlas1", uv = { 0, 0, 0.688965, 0.215332 } }
resource "ImageRegion" "UiMapRainEnd" { image = "UiMapAtlas1", uv = { 0, 0.217285, 0.492676, 0.419922 } }
resource "ImageRegion" "UiMapDuskEnd" { image = "UiMapAtlas1", uv = { 0.494629, 0.217285, 0.947754, 0.522949 } }
resource "ImageRegion" "UiMapDawn_Shrine" { image = "UiMapAtlas1", uv = { 0.494629, 0.524902, 0.89209, 0.903809 } }
resource "ImageRegion" "UiMapCandleSpaceEnd" { image = "UiMapAtlas1", uv = { 0, 0.421875, 0.458496, 0.698242 } }
resource "ImageRegion" "UiMapSunsetColosseum" { image = "UiMapAtlas1", uv = { 0, 0.700195, 0.444824, 0.977051 } }
resourceref "Image" "UiMapAtlas2"

resource "ImageRegion" "UiMapAviaryVillage" { image = "UiMapAtlas2", uv = { 0, 0, 0.370605, 0.265625 } }
resource "ImageRegion" "UiMapNight_StoryBook" { image = "UiMapAtlas2", uv = { 0.372559, 0, 0.724609, 0.256348 } }
resource "ImageRegion" "UiMapDusk_Triangle" { image = "UiMapAtlas2", uv = { 0.372559, 0.258301, 0.714355, 0.477051 } }
resource "ImageRegion" "UiMapPrairie_Island" { image = "UiMapAtlas2", uv = { 0.372559, 0.479004, 0.709961, 0.777832 } }
resource "ImageRegion" "UiMapStorm" { image = "UiMapAtlas2", uv = { 0, 0.267578, 0.366211, 0.748047 } }
resource "ImageRegion" "UiMapDuskOasis" { image = "UiMapAtlas2", uv = { 0, 0.75, 0.34375, 0.902832 } }
resourceref "Image" "UiMapAtlas3"

resource "ImageRegion" "UiMapStormStart" { image = "UiMapAtlas3", uv = { 0, 0, 0.337402, 0.271484 } }
resource "ImageRegion" "UiMapRain" { image = "UiMapAtlas3", uv = { 0, 0.273438, 0.32666, 0.479004 } }
resource "ImageRegion" "UiMapStormEnd" { image = "UiMapAtlas3", uv = { 0.328613, 0.273438, 0.634277, 0.643066 } }
resource "ImageRegion" "UiMapRain_BlueBirdTheater" { image = "UiMapAtlas3", uv = { 0.328613, 0.64502, 0.625488, 0.855469 } }
resource "ImageRegion" "UiMapRain_BaseCamp" { image = "UiMapAtlas3", uv = { 0.63623, 0.273438, 0.937988, 0.45166 } }
resource "ImageRegion" "UiMapSunsetVillage" { image = "UiMapAtlas3", uv = { 0, 0.480957, 0.326172, 0.70752 } }
resource "ImageRegion" "UiMapNight2_SecondFloor" { image = "UiMapAtlas3", uv = { 0, 0.709473, 0.308105, 0.987793 } }
resource "ImageRegion" "UiMapDawn" { image = "UiMapAtlas3", uv = { 0.339355, 0, 0.672363, 0.17041 } }
resource "ImageRegion" "UiMapRainMid" { image = "UiMapAtlas3", uv = { 0.674316, 0, 0.994141, 0.235352 } }
resourceref "Image" "UiMapAtlas4"

resource "ImageRegion" "UiMapNight_PaintedWorld" { image = "UiMapAtlas4", uv = { 0, 0, 0.296387, 0.260742 } }
resource "ImageRegion" "UiMapSunset" { image = "UiMapAtlas4", uv = { 0.29834, 0, 0.588379, 0.185059 } }
resource "ImageRegion" "UiMapPrairie_NestAndKeeper" { image = "UiMapAtlas4", uv = { 0.590332, 0, 0.860352, 0.198242 } }
resource "ImageRegion" "UiMapSunset_Town" { image = "UiMapAtlas4", uv = { 0.590332, 0.200195, 0.859375, 0.390137 } }
resource "ImageRegion" "UiMapNightDesert" { image = "UiMapAtlas4", uv = { 0.590332, 0.39209, 0.854004, 0.624023 } }
resource "ImageRegion" "UiMapSunset_Citadel" { image = "UiMapAtlas4", uv = { 0.590332, 0.625977, 0.852539, 0.833008 } }
resource "ImageRegion" "UiMapNight_Shelter" { image = "UiMapAtlas4", uv = { 0.29834, 0.187012, 0.58252, 0.437012 } }
resource "ImageRegion" "UiMapDayHubCave" { image = "UiMapAtlas4", uv = { 0.29834, 0.438965, 0.577148, 0.567871 } }
resource "ImageRegion" "UiMapRainForest" { image = "UiMapAtlas4", uv = { 0.29834, 0.569824, 0.571777, 0.692383 } }
resource "ImageRegion" "UiMapSunsetRace" { image = "UiMapAtlas4", uv = { 0.29834, 0.694336, 0.569336, 0.828613 } }
resource "ImageRegion" "UiMapRainShelter" { image = "UiMapAtlas4", uv = { 0.29834, 0.830566, 0.560547, 0.998047 } }
resource "ImageRegion" "UiMapCandleSpace" { image = "UiMapAtlas4", uv = { 0, 0.262695, 0.293457, 0.522949 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields" { image = "UiMapAtlas4", uv = { 0, 0.524902, 0.291504, 0.679199 } }
resource "ImageRegion" "UiMapPrairie_Village" { image = "UiMapAtlas4", uv = { 0, 0.681152, 0.290527, 0.915039 } }
resourceref "Image" "UiMapAtlas5"

resource "ImageRegion" "UiMapRain_Town" { image = "UiMapAtlas5", uv = { 0, 0, 0.26123, 0.190918 } }
resource "ImageRegion" "UiMapSkyway" { image = "UiMapAtlas5", uv = { 0, 0.192871, 0.260742, 0.432129 } }
resource "ImageRegion" "UiMapDusk_CrabField" { image = "UiMapAtlas5", uv = { 0, 0.434082, 0.248535, 0.646973 } }
resource "ImageRegion" "UiMapPrairie_WildLifePark" { image = "UiMapAtlas5", uv = { 0, 0.648926, 0.245117, 0.866211 } }
resource "ImageRegion" "UiMapRain_Cave" { image = "UiMapAtlas5", uv = { 0.24707, 0.648926, 0.482422, 0.811523 } }
resource "ImageRegion" "UiMapDawnCave" { image = "UiMapAtlas5", uv = { 0.250488, 0.434082, 0.487305, 0.620605 } }
resource "ImageRegion" "UiMapDuskGraveyard" { image = "UiMapAtlas5", uv = { 0.489258, 0.434082, 0.724609, 0.57959 } }
resource "ImageRegion" "UiMapDuskStart" { image = "UiMapAtlas5", uv = { 0.262695, 0.192871, 0.51416, 0.407227 } }
resource "ImageRegion" "UiMapSunset_Theater" { image = "UiMapAtlas5", uv = { 0.516113, 0.192871, 0.766602, 0.413574 } }
resource "ImageRegion" "UiMapDusk" { image = "UiMapAtlas5", uv = { 0.263184, 0, 0.515137, 0.183594 } }
resource "ImageRegion" "UiMapSunset_YetiPark" { image = "UiMapAtlas5", uv = { 0.51709, 0, 0.765625, 0.139648 } }
resourceref "Image" "UiMapAtlas6"

resource "ImageRegion" "UiMapDuskMid" { image = "UiMapAtlas6", uv = { 0, 0, 0.234863, 0.251953 } }
resource "ImageRegion" "UiMapPrairie_Cave" { image = "UiMapAtlas6", uv = { 0.236816, 0, 0.458496, 0.158691 } }
resource "ImageRegion" "UiMapNight_ThirdFloor" { image = "UiMapAtlas6", uv = { 0.460449, 0, 0.667969, 0.172852 } }
resource "ImageRegion" "UiMapDawn_TrialsEarth" { image = "UiMapAtlas6", uv = { 0.669922, 0, 0.825195, 0.153809 } }
resource "ImageRegion" "UiMapBeaconLines" { image = "UiMapAtlas6", uv = { 0.827148, 0, 0.902344, 0.075195 } }
resource "ImageRegion" "UiMapPlayer" { image = "UiMapAtlas6", uv = { 0.904297, 0, 0.973633, 0.069336 } }
resource "ImageRegion" "UiMapTGCOffice" { image = "UiMapAtlas6", uv = { 0.669922, 0.155762, 0.821289, 0.305176 } }
resource "ImageRegion" "UiMapDawn_TrialsWater" { image = "UiMapAtlas6", uv = { 0.669922, 0.307129, 0.811035, 0.448242 } }
resource "ImageRegion" "UiMapBeaconLinesGlow" { image = "UiMapAtlas6", uv = { 0.669922, 0.450195, 0.762695, 0.542969 } }
resource "ImageRegion" "UiMapBeaconDotGlow" { image = "UiMapAtlas6", uv = { 0.669922, 0.544922, 0.759766, 0.634766 } }
resource "ImageRegion" "UiMapBeaconOutlineGlow" { image = "UiMapAtlas6", uv = { 0.669922, 0.636719, 0.758789, 0.725586 } }
resource "ImageRegion" "UiMapBeaconOutline" { image = "UiMapAtlas6", uv = { 0.669922, 0.727539, 0.74707, 0.804688 } }
resource "ImageRegion" "UiMapBeaconBg" { image = "UiMapAtlas6", uv = { 0.669922, 0.806641, 0.745117, 0.881836 } }
resource "ImageRegion" "UiMapBeaconDot" { image = "UiMapAtlas6", uv = { 0.669922, 0.883789, 0.745117, 0.958984 } }
resource "ImageRegion" "UiMapRainEnd_Pond" { image = "UiMapAtlas6", uv = { 0.460449, 0.174805, 0.654297, 0.313965 } }
resource "ImageRegion" "UiMapDawn_Start" { image = "UiMapAtlas6", uv = { 0.460449, 0.315918, 0.652832, 0.410156 } }
resource "ImageRegion" "UiMapDawn_Plateau" { image = "UiMapAtlas6", uv = { 0.460449, 0.412109, 0.637207, 0.568848 } }
resource "ImageRegion" "UiMapSunsetVillage_MusicShop" { image = "UiMapAtlas6", uv = { 0.460449, 0.570801, 0.625977, 0.68457 } }
resource "ImageRegion" "UiMapDawn_TrialsFire" { image = "UiMapAtlas6", uv = { 0.460449, 0.686523, 0.625, 0.847656 } }
resource "ImageRegion" "UiMapDawn_TrialsAir" { image = "UiMapAtlas6", uv = { 0.460449, 0.849609, 0.611816, 0.996582 } }
resource "ImageRegion" "UiMapStormLight" { image = "UiMapAtlas6", uv = { 0.236816, 0.160645, 0.453125, 0.467285 } }
resource "ImageRegion" "UiMapSunset_FlyRace" { image = "UiMapAtlas6", uv = { 0.236816, 0.469238, 0.450684, 0.585449 } }
resource "ImageRegion" "UiMapIPC_AuroraConcert" { image = "UiMapAtlas6", uv = { 0.236816, 0.587402, 0.447266, 0.772461 } }
resource "ImageRegion" "UiMapNight2" { image = "UiMapAtlas6", uv = { 0.236816, 0.774414, 0.445312, 0.923828 } }
resource "ImageRegion" "UiMapPlayerShadow" { image = "UiMapAtlas6", uv = { 0.236816, 0.925781, 0.306152, 0.995117 } }
resource "ImageRegion" "UiMapSpirit" { image = "UiMapAtlas6", uv = { 0.308105, 0.925781, 0.367676, 0.985352 } }
resource "ImageRegion" "UiMapStar" { image = "UiMapAtlas6", uv = { 0.369629, 0.925781, 0.422363, 0.978516 } }
resource "ImageRegion" "UiMapPath" { image = "UiMapAtlas6", uv = { 0.424316, 0.925781, 0.443848, 0.945312 } }
resource "ImageRegion" "UiMapNightArchive" { image = "UiMapAtlas6", uv = { 0, 0.253906, 0.234375, 0.421387 } }
resource "ImageRegion" "UiMapNight_IPHallway" { image = "UiMapAtlas6", uv = { 0, 0.42334, 0.231934, 0.627441 } }
resource "ImageRegion" "UiMapPrairie_ButterflyFields_Town" { image = "UiMapAtlas6", uv = { 0, 0.629395, 0.230469, 0.776367 } }
resource "ImageRegion" "UiMapNight" { image = "UiMapAtlas6", uv = { 0, 0.77832, 0.228516, 0.935059 } }
